# Generated by Django 4.1.1 on 2022-09-30 06:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('first_name', models.CharField(blank=True, max_length=500)),
                ('last_name', models.CharField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=500, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.country')),
                ('distric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.distric')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.gender')),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.pincode')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.state')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.village')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('referral_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'db_table': 'referral',
            },
        ),
    ]
