# Generated by Django 4.1.1 on 2022-09-30 06:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('country_name', models.CharField(blank=True, default=False, max_length=255)),
                ('country_code', models.CharField(blank=True, default=False, max_length=10)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Distric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'distric',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, default=False, max_length=10)),
            ],
            options={
                'db_table': 'gender',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('person', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('distric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.distric')),
            ],
            options={
                'db_table': 'village',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('state_name', models.CharField(blank=True, default=False, max_length=255)),
                ('state_code', models.CharField(blank=True, default=False, max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.country')),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('user_id', models.CharField(blank=True, default=False, max_length=25)),
                ('first_name', models.CharField(blank=True, default=False, max_length=55)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(blank=True, default=False, max_length=50)),
                ('mobile', models.CharField(blank=True, default=False, max_length=15)),
                ('password', models.CharField(blank=True, default=False, max_length=600)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.person')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.gender')),
            ],
            options={
                'db_table': 'register',
            },
        ),
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('pincode', models.CharField(blank=True, max_length=15, null=True)),
                ('distric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.distric')),
            ],
            options={
                'db_table': 'pincode',
            },
        ),
        migrations.AddField(
            model_name='distric',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.state'),
        ),
    ]
