# Generated by Django 4.1.1 on 2022-09-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='date_of_birthday',
            field=models.DateField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(default=False, max_length=55),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='register',
            name='user_id',
            field=models.CharField(default=False, max_length=25),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
