# Generated by Django 4.1.1 on 2022-09-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_register_date_of_birthday_alter_gender_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='date_of_birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
