# Generated by Django 4.1.1 on 2022-09-30 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_register_date_of_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='date_of_birthday',
        ),
    ]
